CREATE TABLE HVSS_CONTENT_TYPE(
   ID BIGSERIAL NOT NULL primary KEY ,
   NAME VARCHAR  (16) NOT NULL
);

INSERT INTO HVSS_CONTENT_TYPE (NAME) VALUES ('ANIME'), ('ANIME_SERIES'), ('MOVIE'), ('SERIES');

CREATE TABLE HVSS_TORRENT_DATA(
    ID BIGSERIAL NOT NULL primary KEY ,
    UID VARCHAR (36),
    TORRENT_FILEURL VARCHAR (255),
    TORRENT_NAME VARCHAR (255),
    TORRENT_FILE_SAVE_PATH VARCHAR (255),
    DOWNLOADED_CONTENT_SAVE_PATH VARCHAR (255),
    GENERAL_FOLDER_NAME VARCHAR (255),
    TORRENT_CREATION_DATE TIMESTAMP,
    FINISH_DATE TIMESTAMP,
    DELETION_FROM_CLIENT_DATE TIMESTAMP,
    HVSS_TYPE VARCHAR(255)
);

CREATE TABLE HVSS_CONTENT_GROUP(
    ID BIGSERIAL NOT NULL primary KEY ,
    UID VARCHAR (36),
    NAME  VARCHAR (255),
    CONTENT_TYPE_ID VARCHAR(12),
    COVER_PICTURE_LOCAL_PATH VARCHAR(255),
    TORRENT_DATA_ID BIGINT REFERENCES HVSS_TORRENT_DATA(ID),
    TORRENT_VERIFIED BOOLEAN,
    CREATION_DATE TIMESTAMP,
    LAST_UPDATE_DATE TIMESTAMP,
    HVSS_TYPE VARCHAR(255)
);

CREATE TABLE HVSS_USER_TOKEN(
    ID BIGSERIAL NOT NULL primary KEY ,
    UID VARCHAR (36),
    SESSION_TOKEN VARCHAR (36),
    CREATION_DATE TIMESTAMP,
    LAST_UPDATE_DATE TIMESTAMP,
    HVSS_TYPE VARCHAR(255)
);

CREATE TABLE HVSS_USER(
    ID BIGSERIAL NOT NULL primary KEY ,
    UID VARCHAR (36),
    NAME  VARCHAR (255),
    USERNAME VARCHAR(255),
    EMAIL_ADDRESS VARCHAR (255),
    PASSWORD VARCHAR (255),
    PROFILE_PICTURE_PATH VARCHAR (255),
    USER_TOKEN_ID BIGINT REFERENCES HVSS_USER_TOKEN(ID),
    LOGIN_REMEMBER_TOKEN VARCHAR (36),
    CREATION_DATE TIMESTAMP,
    LAST_UPDATE_DATE TIMESTAMP,
    HVSS_TYPE VARCHAR(255)
);

CREATE TABLE HVSS_CONTENT(
    ID BIGSERIAL NOT NULL primary KEY ,
    UID VARCHAR (36),
    CONTENT_GROUP_ID BIGINT REFERENCES HVSS_CONTENT_GROUP(id),
    PRIMARY_LOCATION VARCHAR(7),
    CONTENT_NAME VARCHAR (255),
    COVER_PICTURE_LOCAL_PATH VARCHAR(255),
    CONTENT_DESCRIPTION VARCHAR(255),
    TORRENT_FILE_PATH VARCHAR(255),
    TORRENT_VERIFIED BOOLEAN,
    TORRENT_DATA_ID BIGINT REFERENCES HVSS_TORRENT_DATA(ID),
    TORRENT_VERIFIED BOOL,
    CREATION_DATE TIMESTAMP,
    LAST_UPDATE_DATE TIMESTAMP,
    HVSS_TYPE VARCHAR(255)
);

CREATE TABLE HVSS_CONTENT_ELEMENT(
    ID BIGSERIAL NOT NULL primary KEY ,
    UID VARCHAR (36),
    NAME VARCHAR (255),
    ELEMENT_ORDER INTEGER,
    COVER_PICTURE_LOCAL_PATH VARCHAR(255),
    CONTENT_ID BIGINT REFERENCES HVSS_CONTENT(id),
    TORRENT_DATA_ID BIGINT REFERENCES HVSS_TORRENT_DATA(ID),
    TORRENT_VERIFIED BOOLEAN,
    CREATION_DATE TIMESTAMP,
    LAST_UPDATE_DATE TIMESTAMP,
    HVSS_TYPE VARCHAR(255)
);

CREATE TABLE HVSS_FILE_LOCATION(
    ID BIGSERIAL NOT NULL primary KEY ,
    UID VARCHAR (36),
    CONTENT_ELEMENT_ID BIGINT REFERENCES HVSS_CONTENT_ELEMENT(ID),
    FILE_LOCATION_TYPE VARCHAR(7),
    FILE_PATH VARCHAR (1024),
    SUBTITLE_PATH VARCHAR (1024),
    CREATION_DATE TIMESTAMP,
    LAST_UPDATE_DATE TIMESTAMP,
    HVSS_TYPE VARCHAR(255)
);




