CREATE TABLE HVSS_CONTENT_TYPE(
   ID BIGSERIAL NOT NULL primary KEY ,
   NAME VARCHAR  (16) NOT NULL
);
INSERT INTO HVSS_CONTENT_TYPE (NAME) VALUES ('ANIME'), ('ANIME_SERIES'), ('MOVIE'), ('SERIES');

CREATE TABLE HVSS_CONTENT_GROUP(
    ID BIGSERIAL NOT NULL primary KEY ,
    UID VARCHAR (36),
    NAME  VARCHAR (255),
    CONTENT_TYPE_ID VARCHAR(12),
    CREATION_DATE TIMESTAMP,
    LAST_UPDATE_DATE TIMESTAMP
);

CREATE TABLE HVSS_TORRENT_DATA(
    ID BIGSERIAL NOT NULL primary KEY ,
    UID VARCHAR (36),
    TORRENT_FILEURL VARCHAR (255),
    TORRENT_NAME VARCHAR (255),
    TORRENT_FILE_SAVE_PATH VARCHAR (255),
    DOWNLOADED_CONTENT_SAVE_PATH VARCHAR (255),
    GENERAL_FOLDER_NAME VARCHAR (255),
    TORRENT_CREATION_DATE TIMESTAMP,
    FINISH_DATE TIMESTAMP,
    DELETION_FROM_CLIENT_DATE TIMESTAMP
);


CREATE TABLE HVSS_CONTENT(
    ID BIGSERIAL NOT NULL primary KEY ,
    UID VARCHAR (36),
    CONTENT_GROUP_ID BIGINT REFERENCES HVSS_CONTENT_GROUP(id),
    CONTENT_NAME VARCHAR (255),
    COVER_PICTURE_LOCAL_PATH VARCHAR(255),
    CONTENT_DESCRIPTION VARCHAR(255),
    TORRENT_FILE_PATH VARCHAR(255),
    ARCHIVE_FOLDER_NAME VARCHAR (255),
    TORRENT_DATA_ID BIGINT REFERENCES HVSS_TORRENT_DATA(ID),
    CREATION_DATE TIMESTAMP,
    LAST_UPDATE_DATE TIMESTAMP
);

CREATE TABLE HVSS_CONTENT_ELEMENT(
    ID BIGSERIAL NOT NULL primary KEY ,
    UID VARCHAR (36),
    NAME VARCHAR (255),
    CONTENT_ID BIGINT REFERENCES HVSS_CONTENT(id),
    ARCHIVE_LOCATION_PATH VARCHAR (1024),
    BUFFER_LOCATION_PATH VARCHAR (1024),
    TORRENT_DATA_ID BIGINT REFERENCES HVSS_TORRENT_DATA(ID),
    CREATION_DATE TIMESTAMP,
    LAST_UPDATE_DATE TIMESTAMP
);



